baseURL = 'https://dscamiss.github.io/'
languageCode = 'en-us'
title = 'dscamiss'
theme = 'PaperMod'

[params]
  math = true
  defaultTheme = 'auto'

[menus]
  [[menus.main]]
    name    = 'Home'
    pageRef = '/'
    weight  = 1
  [[menus.main]]
    name    = 'About'
    pageRef = '/about'
    weight  = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

